### ISSUE TITLE
Sampling in parallel

### ISSUE THREAD

**Issue by mcleonard** [mcleonard/sampyl#10]
There needs to be functionality to run multiple chains in parallel. This can be used for convergence testing and for increasing the samples per second you get.

**Comment by andymiller** [comment]
There are two forms of parallel here.  Running multiple, independent chains
(on a single processor) is definitely a good idea - that way we can keep
running convergence statistics.

Running multiple, independent chains on many processors is also a good
idea, but would that require a different solution?

Also, running a single chain with a likelihood that can be executed on many
cores (think many terms in a likelihood function) is useful, but we can
leave it up to the user to implement that and pass in a function handle
that distributes computation.

**Comment by mcleonard** [comment]
Alright, added functionality to the samplers to run multiple chains. API is simple:
    
    nuts = smp.NUTS(logp, start)
    chains = nuts.sample(1000, n_chains=4)

It returns a list of 4 chains. Each chain gets its own process, so the OS decides how to run them. If you have a CPU with 4 cores, it'll run each chain in parallel. If you only have 2 cores, it'll do 2 at a time.
