### ISSUE TITLE
Add ability of logp to return both log posterior and its gradient

### ISSUE THREAD

**Issue by jgomezdans** [mcleonard/sampyl#12]
There are situations where we have access to an analytic form of both the log posterior and its gradient. It is beneficial to use this, as ``autograd`` might not work (e.g. compiled code), or it's just wasteful to calculate both logp and its partial derivatives separately. Methods like e.g. ``fmin_l_bfgs_b`` allow one to provide a function that returns both the cost function and its gradient, or a function that only returns the cost function (with the gradient in their case calculated by finite differences).

**Comment by andymiller** [comment]
This is a great point, and indeed, some of the motivation behind rolling a
new MCMC package is to give the user more control over the likelihood
function (and its gradient).

Right now you can pass in your own separate gradient function (the
`grad_logp=None` argument in the sampler) instead of relying on autograd.

For using a combo function+its gradient, at the moment we don't support
that.  In HMC or NUTS, most of the time we only want to evaluate just the
gradient or just the likelihood, not both, so I don't think we'd gain too
much calculating them simultaneously.
But of course there are other use cases - let us know what you have in mind!

**Comment by jgomezdans** [comment]
Thanks for your answer. I understand that you can pass your own gradient, but it turns out that calculating the likelihood and gradient is in our case prohibitive. We also have a (say) f2py/cython function that returns both ``H`` and ``dH`` that we want to use.
In NUTS, [as far as I can tell] (https://github.com/mcleonard/sampyl/blob/master/sampyl/samplers/NUTS.py#L77), you do need them together. In standard Metropolis and HMC are of course different, but even in that case, we're still using e.g. a compiled function that returns both function and gradient, so it still makes sense being able the same function without further changes to the code. 

I have sort of hacked bits of sampyl to attain this, but it's still dirty/untested/embarrassing, and the interface isn't very clean, but I'll try sending you a PR when I've tested things a bit more.

**Comment by andymiller** [comment]
For NUTS (and HMC) you certainly need both the likelihood and its gradient, but they don't need to be evaluated at the same time (on the same point), as far as I understand.

In HMC, for example, the only time the gradient is needed is to compute the leapfrog trajectory (and you don't need to evaluate the likelihood along the way).  The only time you need the likelihood is to accept/reject the result of the leapfrog trajectory, which doesn't require a gradient.  

In that line it looks like we're just unpacking and storing the function handles logp and dlogp as H and dH (for cosmetic reasons, it looks like).  They aren't being evaluated at that point. 

A not-so-bad way to get around this is to wrap your function that returns a tuple `ll, ll_grad = fun(x)`

```
def logp(x):
  ll, _ = fun(x)
  return ll

def dlogp(x):
  _, grad = fun(x)
  return grad
```
and then pass `logp` and `dlogp` to Sampyl.  It will be a little redundant (it's computing both the value and gradient when it doesn't have to) but if it's efficiently doing so, that's not so bad.  

Is that a sensible solution?

**Comment by jgomezdans** [comment]
I think for NUTS they have to (at least in your code). Not the case for HMC, where the acceptance and leapfrogs are indeed independent. The solution you propose is precisely the kind of behaviour I'm trying to avoid, as in our case, ``fun(x)`` can take "a long time to run", so running it twice is not great.

**Comment by andymiller** [comment]
I think I see what you're saying now, and you're totally right - I was misunderstanding before.  

For instance on page 1364 of [the nuts paper](http://www.stat.columbia.edu/~gelman/research/published/nuts.pdf), the base case of `build_tree` involves a leapfrog that ends on `\theta'` (meaning it evaluated the gradient on `\theta'`), and then it evaluates the likelihood on `\theta'`, an operation that has already been done by your code.  
So the offending line of code is [here](https://github.com/mcleonard/sampyl/blob/master/sampyl/samplers/NUTS.py#L129) - this energy value has already been computed by your function, it's just not accessible.  

Am I understanding this correctly?  Are there other parts of the algorithm that you've caught that are redundant?  If so - this is a great catch and thanks so much for pointing it out!  That seems like something we should optimize for NUTS and keep in mind for future MCMC routines that use gradient information.

**Comment by mcleonard** [comment]
Sweet, I can see where our NUTS algorithm can be improved here:

    x1, r1 = leapfrog(x, r, v*e, dH)
    E = energy(H, x1, r1)
    E0 = energy(H, x0, r0)

We calculate the energy and the gradient at both x0 and x1, so I just need to modify the leapfrog algorithm to return the energies too. Something like

    x1, r1, E, E0 = leapfrog_E(x, r, v*e, H)

I can bundle the cost function and gradient into an object `H` so it works the same way if they come from one function or two.

Thanks José!

**Comment by jgomezdans** [comment]
Regarding the bundling you speak of at the end (and my original request), I was trying to do this using a memoize pattern, such as is [done in scipy.optimize](https://github.com/scipy/scipy/blob/v0.16.0/scipy/optimize/optimize.py#L53), ought to save passing more variables around, but maybe in this case, your solution is easier.

**Comment by mcleonard** [comment]
After I worked on this for a bit last night, I found some issues. For each call to `build_tree`, there are two calls to logp and two calls to grad_logp. Below is the relevant code.

    def buildtree(x, r, u, v, j, e, x0, r0, H, dH, Emax):
        if j == 0:
            x1, r1 = leapfrog(x, r, v*e, dH)
            E = energy(H, x1, r1)
            E0 = energy(H, x0, r0)
            .....

    def leapfrog(x, r, step_size, grad_logp):
        r1 = r + step_size/2*grad_vec(grad_logp, x)
        x1 = x + step_size*r1
        r2 = r1 + step_size/2*grad_vec(grad_logp, x1)
        return x1, r2

    def energy(logp, x, r):
        r1 = r.tovector()
        return logp(*x.values()) - 0.5*np.dot(r1, r1)

There are three states involved here, *x0*, *x*, and *x1*. The calls we make are logp(*x1*), logp(*x0*), grad_logp(*x*), and grad_logp(*x1*). So, if we call a function that returns logp and grad_logp together, we are wasting computation on logp(*x0*) and grad_logp(*x*). Because of this, I think caching the results of the function calls is the way to go.

I'm not sure if this will speed up your usage much, since there seem to be wasted calls. But I'll add the caching and we can see if it improves.

**Comment by mcleonard** [comment]
Okay, I changed how the internals work to get this going. The whole thing is better now and it should make it more simple to create new samplers in the future. The pull request is here: https://github.com/mcleonard/sampyl/pull/13. It is the branch issue_12_combo_logp if you want to test it out.

**Comment by jgomezdans** [comment]
It appears to be working OK, both with with the combined log posterior, cache and even with parallel!

**Comment by mcleonard** [comment]
Coolio, I'll merge it then.
